DT_ClauseParticle = ["啊都",
                     "嗚呼",
                     "oo-hoo",
                     "--hioh",
                     "--lah",
                     "--neh",
                     "--leh",
                     "--looh",
                     "--lih",
                     "--honnh",
                     "--nih",
                     "--ooh",
                     "--ah",
                     "--mah",
                     "--ê"]